extensions:
  # health check is used by load balancers and the like to determine if the collector is running and healthy
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
#  debug:
#    verbosity: detailed

  awsemf: #AWS (CloudWatch) Embedded Metric Format
    region: us-east-1
    namespace: fargate-ecr-otel-poc-metrics
    log_group_name: fargate-ecr-otel-poc-metrics

  awscloudwatchlogs:
    region: us-east-1
    log_group_name: fargate-ecr-otel-poc-logs
    log_stream_name: fargate-ecr-otel-poc-stream

  awsxray:
    region: us-east-1

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsemf]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [awscloudwatchlogs]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]