receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
#  resource:
#    attributes:
#      - key: service.name
#        from_attribute: service.name
#        action: upsert
#      - key: deployment.environment
#        from_attribute: deployment.environment
#        action: upsert
  resource_to_telemetry_conversion:
    enabled: true

exporters:
#  debug:
#    verbosity: detailed

  awsemf: #AWS (CloudWatch) Embedded Metric Format
    region: us-east-1
    namespace: "fargate-ecr-otel-poc-metrics"

  awscloudwatchlogs:
    region: us-east-1
    log_group_name: "fargate-ecr-otel-poc-logs"
    log_stream_name: "fargate-ecr-otel-poc-stream"

  awsxray:
    region: us-east-1

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, resource_to_telemetry_conversion]
      exporters: [awsemf]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [awscloudwatchlogs]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]